### ISSUE TITLE
Articles?author=johnjacob not returning article

### ISSUE THREAD

**Issue by Cameron-C-Chapman** [aisensiy/realworld-spring-boot#1]
When you search for articles by author results are not returned.
![screenshot 2017-08-18 09 51 52](https://user-images.githubusercontent.com/1323581/29464235-e465bb92-83fa-11e7-8b9c-ee5b5ab403fa.png)
![screenshot 2017-08-18 09 52 14](https://user-images.githubusercontent.com/1323581/29464258-f93714ee-83fa-11e7-8896-fa0c70a9cc3b.png)

**Comment by aisensiy** [comment]
Thanks for your feedback, its already fixed.
